CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE iam;
CREATE DATABASE customer;
CREATE DATABASE vendor;

GRANT ALL PRIVILEGES ON DATABASE iam TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE customer TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE vendor TO oeuser;