---
servers:
- url: "http://localhost:8080"
openapi: "3.0.1"
paths:
  /customers/{id}:
    $ref: "./customer.yaml#/paths/~1customers~1{id}"
  /customers:
    $ref: "./customer.yaml#/paths/~1customers"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
